[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault_program = "4B4n1NxmqPy5muRbQYafVotCnS4pg4Wh9hb1TDxqkfAW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 60000
rpc = "http://127.0.0.1:8898"